# Generated by Django 5.0.6 on 2024-06-29 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordselector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='document',
        ),
        migrations.AddField(
            model_name='coordinate',
            name='pdf_document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='coordselector.pdfdocument'),
            preserve_default=False,
        ),
    ]
